# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35e1aa99695be3b2737ac2a6940c94c7fd6a5085cda99ddb56eb855cf7acd86d52de0d71723080d6120507a25a775cb284042828ffe57f5016fc2415e3af36f2

test:
  secret_key_base: e1cd5e504f10f49bf216f5b8e43228d9d952aa3abf8394d1fdab19bc48cbb4c04478eeae7f40dd698e82e5ddbb0b2601a3c918d8707adfd66040b3812d5591ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
